site_name: Matt Rayson's homepage
docs_dir: docs/
site_dir: site/

repo_url: https://github.com/mrayson/mrayson.github.io

pages:
- Home: 'index.md'
- Publications: 'Publications.md'
- CV: 'CV.md'
- Research: 'Research.md'
- Ocean Modelling: 'oceanmodelling.md'
- Internal Waves: 'internalwaves.md'


theme: spacelab
